<?php

declare(strict_types=1);

namespace Cekta\DI\Test\AcceptanceTest;

class AutowiringInConstructor
{
    /**
     * @var int[]
     */
    public array $variadic_int;

    public function __construct(
        public string $username,
        public string $password,
        public Shared $exampleShared, // other entrypoint must be available
        public A $a,  // container only for this container must be created with new
        public I $i, // interface
        public S $s, // shared containers must be reusable
        public S | string $union_type, // union_type container must work start with php8.0
        public string $dsn, // generated by definition from other dependencies
        int ...$variadic_int
    ) {
        $this->variadic_int = $variadic_int;
    }
}
