<?php

declare(strict_types=1);

namespace Cekta\DI\Test\AcceptanceTest;

class EntrypointAutowiring
{
    /**
     * @var int[]
     */
    public array $variadic_int;

    public function __construct(
        public string $username,
        public string $password,
        public ContainerCreatedWithNew $created_with_new,  // container only for this container must be created with new
        public I $i, // alias for interface
        public S $s, // fixme need correc comment
        public S $s2, // fixme need correc comment
        public S $s3, // fixme need correc comment
        public S $s4, // fixme need correc comment
        public S | string $union_type, // union_type container must work start with php8.0
        public string $dsn, // generated by definition from other dependencies
        public EntrypointSharedDependency $exampleShared, // other entrypoint must be available
        int ...$variadic_int
    ) {
        $this->variadic_int = $variadic_int;
    }
}
