jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: install
#        env:
#          TOKEN: ${{ secrets.TOKEN }}
        run: make install
      - name: before_script
        run: make before_script
      - name: script
        run: make script
      - name: after_script
        run: make after_script
on:
  pull_request:
    branches:
      - master