jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
      - name: install
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make install
      - name: phpcs
        run: make phpcs
on:
  pull_request:
    branches:
      - master