jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: install
        run: make install
      - name: test
        run: make test

on:
  pull_request:
    branches:
      - master
